//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitap1207.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DuongVanHao_2210900099Entities : DbContext
    {
        public DuongVanHao_2210900099Entities()
            : base("name=DuongVanHao_2210900099Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DuongVanHao_SACH> DuongVanHao_SACH { get; set; }
        public virtual DbSet<DuongVanHao_TACGIA> DuongVanHao_TACGIA { get; set; }
    }
}
