//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitap1207.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuongVanHao_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DuongVanHao_TACGIA()
        {
            this.DuongVanHao_SACH = new HashSet<DuongVanHao_SACH>();
        }
    
        public int DuongVanHao_MaTG { get; set; }
        public string DuongVanHao_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuongVanHao_SACH> DuongVanHao_SACH { get; set; }
    }
}
