//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitap1207.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuongVanHao_SACH
    {
        public int DuongVanHao_MaSach { get; set; }
        public string DuongVanHao_TenSach { get; set; }
        public Nullable<int> DuongVanHao_SoTrang { get; set; }
        public Nullable<System.DateTime> DuongVanHao_NamXB { get; set; }
        public Nullable<int> DuongVanHao_MaTG { get; set; }
        public Nullable<bool> DuongVanHao_TrangThai { get; set; }
    
        public virtual DuongVanHao_TACGIA DuongVanHao_TACGIA { get; set; }
    }
}
